Lazy-initialize SubdomainRouter to avoid rake errors.
When the database is empty, the app crashes and I can't initialize the database. This is because the SubdomainRouter attempts to connect to the database... that doesn't exist yet.

$ rake db:setup
WARNING: 'require 'rake/rdoctask'' is deprecated.  Please use 'require 'rdoc/task' (in RDoc 2.4.2+)' instead.
    at /Users/weppos/.rvm/gems/ruby-1.9.2-p290@minegems/gems/rake-0.9.2.2/lib/rake/rdoctask.rb
minegems_test already exists
minegems_development already exists
rake aborted!
PGError: ERROR:  relation "subdomains" does not exist
LINE 4:              WHERE a.attrelid = '"subdomains"'::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"subdomains"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum

Tasks: TOP => db:setup => db:schema:load => environment
(See full trace by running task with --trace)